config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Root
  root 'landing_pages#index'

  resources :jobs do
    member do
      put "like", to: "jobs#upvote"
      put "dislike", to: "jobs#downvote"
    end
    collection do
      get 'search'
    end
  end

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :jobs

  def sync
    (1..7).each do |index|
      #@url = "http://www.104.com.tw/i/apis/jobsearch.cfm?kws=#{params[:search]}&page=1&pgsz=2000&area=6001001000&order=2&fmt=8&cols=J,JOB,ADDRESS,LINK,APPEAR_DATE,NAME,NEED_EMP,NEED_EMP1,SAL_MONTH_LOW,SAL_MONTH_HIGH"
      @url = "http://www.104.com.tw/i/apis/jobsearch.cfm?kws=&area=6001001000&pgsz=2000&order=2&fmt=8&cols=J,JOB,NAME&page=#{index}"
      @result = JSON.parse(Net::HTTP.get_response(URI.parse(URI.encode(@url))).body)
      @result['data'].each do |data|
        sync_method data
      end
    end
  end

  def sync_method data
    @company = Company.find_or_initialize_by(name: data['NAME'])
    @company.name = data['NAME']
    @company.address = data['ADDRESS']
    @company.site = data['LINK']
    @company.save!

    @job = @company.jobs.find_by_uuid(data['J'])
    if @job.blank?
      @job = @company.jobs.find_or_initialize_by(name: data['JOB'])
    end
    @job.company_id = @company.id
    @job.uuid = data['J']
    @job.name = data['JOB']
    @job.appear_date = data['APPEAR_DATE']
    @job.save!

    @records = @job.records.build
    @records.status = "true"
    @records.pay_low = data['SAL_MONTH_LOW']
    @records.pay_high = data['SAL_MONTH_HIGH']
    @records.need_min = data['NEED_EMP']
    @records.need_max = data['NEED_EMP1']
    @records.record_date = (Date.today)
    @records.save!
  end
end

app/models/company_rate.rb
class CompanyRate < ScoreDetail
  # 公司評分
end

app/models/job.rb
class Job < ActiveRecord::Base
  acts_as_votable
  belongs_to :company
  has_many :records
  has_many :scores

  def self.all_vote
    (Job.all.collect{ |job| job.get_upvotes.size }.sum.to_f / Job.all.collect{ |job| job.votes_for.size }.sum.to_f) * 100 
    
  end

  def score
    return nil unless scores.present?
    scores.last
  end

  def record
    return nil unless records.present?
    records.last
  end

  def paid_str
    return "無資料" unless records.present?

    return_str = "#{records.last.try(:pay_low)}" || '0'

    if records.last.try(:pay_high) > 0
      return_str << " ~ #{records.last.try(:pay_high)}"
    else
      return_str << "以上"
    end

    return return_str
  end
end

app/models/netizen_rate.rb
class NetizenRate < ScoreDetail
  # 公司評分
end

app/models/popular_rate.rb
class PopularRate < ScoreDetail
  # 熱門度
end

app/models/record.rb
class Record < ActiveRecord::Base
  belongs_to :job

  def paid_str
    return "無資料" unless present?

    return_str = "#{pay_low}" || '0'

    if pay_high && pay_high > 0
      return_str << " ~ #{pay_high}"
    else
      return_str << "以上"
    end

    return return_str
  end

    def need_str
    return "無資料" unless present?

    return_str = "#{need_min}" || '0'

    if need_max && need_max > 0
      return_str << " ~ #{need_max}"
    else
      return_str << "以上"
    end

    return return_str
  end
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :job
  has_many :score_details
  has_many :netizen_rates
  has_many :company_rates
  has_many :turnover_rates
  has_many :popular_rates

  def turnover_rate
    return nil unless turnover_rates.present?
    turnover_rates.last
  end

  def netizen_rate
    return nil unless netizen_rates.present?
    netizen_rates.last
  end

  def company_rate
    return nil unless company_rates.present?
    company_rates.last
  end

  def popular_rate
    return nil unless popular_rates.present?
    popular_rates.last
  end

end

app/models/score_detail.rb
class ScoreDetail < ActiveRecord::Base
  belongs_to :score
  validates_presence_of :score
end

app/models/turnover_rate.rb
class TurnoverRate < ScoreDetail
  # 離職率
  def self.median
    array = []
    find_each(:batch_size => 1000) do |rate|
      array << rate.number if rate.number.present?
    end
    array = array.sort!

    elements = array.count
    return 0 if elements < 1
    center =  elements / 2
    return elements.even? ? (array[center - 1] + array[center])/2 : array[center - 1]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!, :only => [:upvote, :downvote]
  def index
    if params[:company_id].present?
      @jobs = Job.where(company_id: params[:company_id]).limit(10).order('RAND()')
    else
      @jobs = Job.where('name like ?',"%#{params[:name]}%").limit(10).order('RAND()')
      @companies = Company.where('name like ?', "%#{params[:name]}%").limit(10).order('RAND()')
    end
  end

  def show
    @job = Job.find(params[:id])
    @recommend_jobs = Job.where('name like ? AND id != ?', "%#{@job.name[0..3]}%", @job.id)
  end

  def score
    @days = (1.days.ago.to_date..Date.today).map{ |date| date.strftime("%Y-%m-%d") }
    @exist_day = 0
    Job.find_each(:batch_size => 1000) do |jobs|

      @days.each do |day|
        @record = Record.find_by(job_id: jobs.id, record_date: '2016-04-30')

        if !@record.status.blank?
          @exist_day = @exist_day + 1
        end
      end
      @total_day = 30.0
      @number = (@exist_day / @total_day) * 100

      score = jobs.scores.build(total: 0)
      score.save!
      score.turnover_rates.build(number: @number).save!
      @exist_day = 0
    end
  end

  #找出所有職缺分數的中位數
  def median
    array = []
    TurnoverRate.find_each(:batch_size => 1000) do |rate|
      array << rate.number
    end
    array = array.sort!
    elements = array.count
    center =  elements / 2
    result = elements.even? ? (array[center] + array[center+1])/2 : array[center]
  end

  def upvote
    @job = Job.find(params[:id])
    @job.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @job = Job.find(params[:id])
    @job.downvote_by current_user
    redirect_to :back
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/landing_pages_helper.rb
module LandingPagesHelper
end

app/views/jobs/_companies.html.erb
<div class="col s12 m8 push-m2 main-list" style="margin-top:3em;">
  <div class="col s6">
    <h6 class="grey-text text-darken-3" style="font-size:20px;">公司</h6>
  </div>
  <div class="col s6">
    <%=link_to jobs_path(name: params[:name], type: 'C') do %>
    <p class="right grey-text" style="margin:0;">更多..</p>
    <%end%>
  </div>
</div>
<div class="col s12 m8 push-m2 white ">
  <ul class="collection">
    <%=render partial: 'company', collection: @companies, as: :company%>
  </ul>
</div>

app/views/jobs/_company.html.erb
<li class="collection-item avatar company">
  <%=link_to jobs_path(company_id: company.id, type: 'J'), data: { no_turbolink: true } do %>
  <span class="title"><%=company.name%></span>
  <%end%>
  <p><%=company.address%><br>
    <%=company.phone%>
  </p>
  <%=link_to company.site, class: ' secondary-content', target: '_blank' do %>
  <i class="material-icons">web</i>
  <%end%>
</li>

app/views/jobs/_job.html.erb
<li class="collection-item avatar">
  <i class="circle green">
  <% if job.score.total > 9.9 %>
  <%=job.score.total.round(1) - 1.0 %>
  <% else %>
  <%=job.score.total.round(1)%>
  <% end %></i>
  <%=link_to job_path(job.id), data: { no_turbolink: true } do %>
  <span class="title"><%=job.name%></span>
  <%end%>
  <p><%=job.company.name%><br>
    <%=job.record.paid_str%>
  </p>
  <%=link_to nil, class: 'secondary-content' do %>
  <%=job.appear_date%>
  <%end%>
</li>

app/views/jobs/_job_block.html.erb
<%=link_to job_path(job.id), data: { no_turbolink: true } do %>
<li class="collection-item avatar">
  <i class="circle green">
   <% if job.score.total > 9.9 %>
    <%=job.score.total.round(1) - 1.0 %>
    <% else %>
    <%=job.score.total.round(1)%>
   <% end %>
   </i>
  <span class="title"><%=job.name%></span>
  <p>
    <%=job.record.paid_str%>
  </p>
</li>
<%end%>

app/views/jobs/_jobs.html.erb
<div class="col s12 m8 push-m2">
  <div class="col s6">
    <h6 class="grey-text text-darken-3" style="font-size:20px;">職缺</h6>
  </div>
  <div class="col s6">
    <%=link_to jobs_path(name: params[:name], type: 'J') do %>
    <p class="right grey-text" style="margin:0;">更多..</p>
    <%end%>
  </div>
</div>
<div class="col s12 m8 push-m2 white ">
  <ul class="collection">
    <%=render partial: 'job', collection: @jobs, as: :job%>
  </ul>
</div>

app/views/jobs/_recommend_job.html.erb
<div class="col s6">
  <div class="card grey lighten-5">
    <div class="card-content">
      <%=link_to job_path(job.id), data: { no_turbolink: true } do %>
      <span class="card-title"><%=job.name%></span>
      <%end%>
      <p><%=job.company.name%></p>
    </div>
    <div class="card-action">
      <a><%=job.record.paid_str%></a>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<%=render partial: 'shared/nav_bar'%>
<div class="container" style="min-height:calc(100vh - 124px);">
  <div class="row">
    <div class="col s12 m8 push-m2 main-list">
      <h5>關鍵字：<%=params[:name]%></h5>
    </div>
    <%=render partial: 'jobs' if %w(J A).include?(params[:type])%>
    <%=render partial: 'companies' if %w(C A).include?(params[:type])%>
  </div>
</div>
<footer class="page-footer grey">
  <div class="container">
    <a class="black-text" href="http://unnamed.taipei">© 2016 Unnamed Studio</a>
    <a class="grey-text text-lighten-4 right" href="mailto:g8071107@gmail.com">Contant Us.</a>
  </div>
</footer>

app/views/jobs/search.html.erb
<%= @recordcount %>
<br>
<%= @pagecount %>
<br>
當前頁數<%= @page %>
<br>
總頁數<%= @totalpage %>
<br>
<hr>
<% @datas.each do |data| %>
代碼 <%= data['J'] %>
<br>
工作 <%= data['JOB'] %>
<br>
名稱 <%= data['NAME'] %>
<br>
職缺張貼時間 <%= data['APPEAR_DATE']%>
<br>
最低需求人次 <%= data['NEED_EMP']%>
<br>
最高需求人次 <%= data['NEED_EMP1']%>
<%= data['ADDRESS']%>
<hr>
<% end %>

app/views/jobs/show.html.erb
<%= javascript_include_tag "highcharts.js", "chartkick" %>
<%=render partial: 'shared/nav_bar'%>
<div class="container">
  <div class="row">
    <div class="col s12 main-list">
      <h4><%=@job.name%></h4>
      <h5 class="grey-text text-darken-3"><%=@job.company.name%></h5>
    </div>
    <div class="col s12">
      <div class="col s12 m4 white">
        <p class="grey-text text-darken-1">
          <i class="material-icons">place</i>
          <%=@job.company.name%><br>
          <i class="material-icons">phone</i>
          <%=@job.company.phone%>
        </p>
        <h6><i class="material-icons">arrow_drop_down</i> 本公司其他職缺</h6>
        <ul class="collection">
          <%=render partial: 'job_block', collection: @job.company.jobs, as: :job%>
        </ul>
      </div>
      <div class="col s12 m8 company-data">
        <div class="col s6"><h5 class="company-data"><i class="material-icons">work</i> 職缺資料</h5></div>
        <div class="col s6"><h5 class="company-data right">
          <%= link_to like_job_path(@job), method: :put, class: "waves-effect waves-light btn white grey-text text-darken-3" do %>
          <i class="material-icons left green-text">thumb_up</i>讚<%= @job.get_upvotes.size %>
          <% end %>
          <%= link_to dislike_job_path(@job), method: :put, class: "waves-effect waves-light btn white grey-text text-darken-3" do %>
          <i class="material-icons left red-text">thumb_down</i>幹<%= @job.get_downvotes.size %>
          <% end %>
        </h5></div>
        <%= bar_chart({"熱門度" => @job.score.popular_rate.number, "離職率" => @job.score.turnover_rate.number, "網友評分" => @job.score.netizen_rate.number, "公司評分" => @job.score.company_rate.number}, discrete: true, library: {chart: {backgroundColor: nil}}) %>
        <%#= pie_chart Goal.group(:name).count %>
        <br> <br> <br>
        <hr>
        <div class="col s6">
          <h6 class="company-data"><i class="material-icons">attach_money</i>薪資</h5>
          <p><%=@job.record.paid_str%></p>
        </div>
        <div class="col s6">
          <h6 class="company-data"><i class="material-icons">people</i> 需要人數</h5>
          <p><%=@job.record.need_str%></p>
        </div>
        <h6 class="company-data"><i class="material-icons">description</i> 說明</h5>
        <p><%=@job.record.description%>
        </p>
        <hr>
        <h6 class="company-data"><i class="material-icons">description</i> 友站連結</h5>
        <p><%=link_to 'http://www.badboss.taipei', 'http://www.badboss.taipei/company/三立電視股份有限公司' if @job.company_id == 986 %></p>
        <hr>
        <h6 class="company-data"><i class="material-icons">arrow_drop_down</i> 相關職缺</h6>
        <div class="row related">
          <%=render partial: 'recommend_job', collection: @recommend_jobs, as: :job%>
        </div>
      </div>
    </div>
  </div>
</div>
<footer class="page-footer grey">
  <div class="container">
    <a class="black-text" href="http://unnamed.taipei">© 2016 Unnamed Studio</a>
    <a class="grey-text text-lighten-4 right" href="mailto:g8071107@gmail.com">Contant Us.</a>
  </div>
</footer>

app/views/landing_pages/index.html.erb
<nav class="transparent">
  <ul class="right hide-on-med-and-down">
  </ul>
  <ul id="slide-out" class="side-nav">
    <li><%=link_to '公司列表', jobs_path(name: params[:name], type: 'C')%></li>
    <li><%=link_to '工作列表', jobs_path(name: params[:name], type: 'J')%></li>
  <% if !current_user %>
    <il><%= link_to "註冊", new_user_registration_path %></li>
    <li><%= link_to "登入", new_user_session_path %></li>
  <% else %>
    <li><%= link_to "登出", destroy_user_session_path, method: :delete %></li>
  <% end %>
  </ul>
</nav>

<div class="container header">
  <div class="row header">
    <div class="col m3 l6 s12">
      <%=image_tag 'logo'%>
    </div>
    <div class="col l6"><a href="#" data-activates="slide-out" class="button-collapse white-text right"><i class="material-icons">menu</i></a></div>

    <div class="col m10 s12 subtitle">
      <h4 class="white-text">從資料找出好職缺<br>讓 Career Inspector 找出屬於你的好位置。</h4>
    </div>
    <div class="col m10 s12 subsubtitle">
      <p class="white-text">初出社會，縱使沒有「慧根」，也要懂得「會跟」；或是您正在轉換跑道，在茫茫職缺海中，不知道哪一份工作適合您的個性與專長？
        <br>
        Career Inspector透過資料分析，找出您最在意的職缺流動率、職缺熱門度，透過我們的分析，面向名為適才適所的晨曦。
      </p>
    </div>
    <div class="col push-m3 m6 s12 search">
      <%= form_tag jobs_path , method: :get do %>
      <div class="input-group">
        <p>輸入關鍵字試試看</p>
        <%= hidden_field_tag :type, 'A'%>
        <%= text_field_tag :name%>
        <%= submit_tag '找工作', class: "btn blue-grey"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

<footer class="page-footer transparent">
    <div class="container">
      <a class="grey-text text-darken-5" href="http://unnamed.taipei">© 2016 Unnamed Studio</a>
      <br>
      <a class="grey-text text-darken-5" href="mailto:g8071107@gmail.com">Contant Us</a>
    </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CareerInscpector</title>
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Let browser know website is optimized for mobile-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', params[:controller], 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body class="grey lighten-4">
    <%= yield %>
  </body>
</html>

app/views/shared/_nav_bar.html.erb
<style>
.btn{
box-shadow: none;
}
</style>
<div class="navbar-fixed">
  <nav class="white">
    <div class="nav-wrapper container">
      <%= link_to root_path, class: 'brand-logo' do %>
      <%= image_tag 'logo-b'%>
      <%end%>
      <a href="#" data-activates="slide-out" class="button-collapse grey-text"><i class="material-icons">menu</i></a>
      <ul class="side-nav" id="slide-out">
        <li><%=link_to '公司列表', jobs_path(name: params[:name], type: 'C'), class: "grey-text text-darken-3"%></a></li>
        <li><%=link_to '職缺列表', jobs_path(name: params[:name], type: 'J'), class: "grey-text text-darken-3"%></li>
        <% if !current_user %>
      <il><%= link_to "註冊", new_user_registration_path, class: "grey-text text-darken-3" %></li>
      <li><%= link_to "登入", new_user_session_path, class: "grey-text text-darken-3" %></li>
      <% else %>
      <li><%= link_to "登出", destroy_user_session_path, method: :delete, class: "grey-text text-darken-3" %></li>
      <% end %>
    </ul>
    <ul class="right hide-on-med-and-down">
      <li><%=link_to '公司列表', jobs_path(name: params[:name], type: 'C'), class: "grey-text text-darken-3"%></a></li>
      <li><%=link_to '職缺列表', jobs_path(name: params[:name], type: 'J'), class: "grey-text text-darken-3"%></li>
      <% if !current_user %>
    <il><%= link_to "註冊", new_user_registration_path, class: "grey-text text-darken-3" %></li>
    <li><%= link_to "登入", new_user_session_path, class: "grey-text text-darken-3" %></li>
    <% else %>
    <li><%= link_to "登出", destroy_user_session_path, method: :delete, class: "grey-text text-darken-3" %></li>
    <% end %>
  </ul>
</div>
</nav>
</div>